query:
  name: "Query AI Agent with Home Assistant context"
  description: "Run a custom AI prompt against your Home Assistant state dump."
  fields:
    prompt:
      description: "The question or instruction to send to the AI model."
      example: "Turn on all the lights in the living room"
    model:
      description: "The AI model to use for the query. If not provided, the default model for the provider will be used."
      example: "gpt-4"
    provider:
      description: "The AI provider to use (openai, llama, gemini, openrouter)"
      example: "openai"
      default: "openai"
      selector:
        select:
          options:
            - "openai"

create_dashboard:
  name: "Create Dashboard via AI Agent"
  description: "Create a new Home Assistant dashboard using AI assistance."
  fields:
    dashboard_config:
      description: "The dashboard configuration as a JSON object."
      example: '{"title": "My Dashboard", "url_path": "my-dashboard", "views": []}'
    provider:
      description: "The AI provider to use (openai, llama, gemini, openrouter)"
      example: "openai"
      default: "openai"
      selector:
        select:
          options:
            - "openai"

create_automation:
  name: "Create Automation via AI Agent"
  description: "Create a new Home Assistant automation using AI assistance."
  fields:
    automation:
      description: "The automation configuration as a JSON object."
      example: '{"alias": "Turn off lights at 9 PM", "trigger": [{"platform": "time", "at": "21:00:00"}], "action": [{"service": "light.turn_off", "target": {"entity_id": "light.living_room"}}]}'
    provider:
      description: "The AI provider to use (openai, llama, gemini, openrouter)"
      example: "openai"
      default: "openai"
      selector:
        select:
          options:
            - "openai"

update_dashboard:
  name: "Update Dashboard via AI Agent"
  description: "Update an existing Home Assistant dashboard using AI assistance."
  fields:
    dashboard_url:
      description: "The URL path of the dashboard to update."
      example: "my-dashboard"
    dashboard_config:
      description: "The updated dashboard configuration as a JSON object."
      example: '{"title": "Updated Dashboard", "views": []}'
    provider:
      description: "The AI provider to use (openai, llama, gemini, openrouter)"
      example: "openai"
      default: "openai"
      selector:
        select:
          options:
            - "openai"

security_validate:
  name: "Validate Input Security"
  description: "Validate input data for security threats and sanitization."
  fields:
    input:
      description: "The input data to validate for security threats."
      example: "Turn on all the lights in the living room"
      required: true
    type:
      description: "The type of input validation to perform."
      example: "general"
      default: "general"
      selector:
        select:
          options:
            - "general"
            - "prompt"
            - "filename"
            - "url"
            - "mcp_command"
            - "api_key"