name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Locate Home Assistant manifest.json
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          MANIFEST="$(find "$GITHUB_WORKSPACE" -maxdepth 6 -path '*/custom_components/*/manifest.json' | head -n1 || true)"
          if [[ -z "$MANIFEST" ]]; then
            echo "No manifest.json found under custom_components/*" >&2
            exit 1
          fi
          INTEGRATION_DIR="$(dirname "$MANIFEST")"
          INTEGRATION_NAME="$(basename "$INTEGRATION_DIR")"
      
          # Also provide *relative* paths for containerized steps (yq)
          MANIFEST_REL="${MANIFEST#"$GITHUB_WORKSPACE/"}"
          INTEGRATION_DIR_REL="${INTEGRATION_DIR#"$GITHUB_WORKSPACE/"}"
      
          echo "manifest=$MANIFEST" >> "$GITHUB_OUTPUT"
          echo "integration_dir=$INTEGRATION_DIR" >> "$GITHUB_OUTPUT"
          echo "integration_name=$INTEGRATION_NAME" >> "$GITHUB_OUTPUT"
          echo "manifest_rel=$MANIFEST_REL" >> "$GITHUB_OUTPUT"
          echo "integration_dir_rel=$INTEGRATION_DIR_REL" >> "$GITHUB_OUTPUT"
      
      - name: Adjust version number in manifest.json
        uses: mikefarah/yq@v4.44.3
        with:
          # Use the *relative* path so it resolves inside /github/workspace
          cmd: >
            yq -i -o=json
            '.version = "${{ github.event.release.tag_name }}"'
            '${{ steps.locate.outputs.manifest_rel }}'
      
      - name: ZIP the integration directory
        id: zip
        shell: bash
        run: |
          set -euo pipefail
          ZIP_OUT="$GITHUB_WORKSPACE/${{ steps.locate.outputs.integration_name }}.zip"
          (cd "${{ steps.locate.outputs.integration_dir }}" && zip -r "$ZIP_OUT" .)
          echo "zip_path=$ZIP_OUT" >> "$GITHUB_OUTPUT"
      
      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip.outputs.zip_path }}